GLS_BlazorMVC_PoC/Controllers/PasswordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GLS_BlazorMVC_PoC.Data;
using GLS_BlazorMVC_PoC.Models;
using Microsoft.AspNetCore.Authorization;
using GLS_BlazorMVC_PoC.FluentValidators;

namespace GLS_BlazorMVC_PoC.Controllers
{
    [Authorize()]
    public class PasswordsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MyDbContext _context;

        public PasswordsController(MyDbContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Passwords
        public async Task<IActionResult> Index()
        {
            var myDbContext = _context.Passwords.Where(p => p.User.Email == User.Identity.Name);
            return View(await myDbContext.ToListAsync());
        }

        // GET: Passwords/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Passwords == null)
            {
                return NotFound();
            }

            var password = await _context.Passwords
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (password == null)
            {
                return NotFound();
            }

            if (password.UserId != _context.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault().Id)
            {
                return Unauthorized();
            }

            return View(password);
        }

        // GET: Passwords/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Passwords/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ServiceName,EncryptedPassword,UserId")] Password password)
        {
            PasswordValidator passValidation = new PasswordValidator();
            FluentValidation.Results.ValidationResult validationResult = passValidation.Validate(password);
            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError("UserError", error.ErrorMessage);
                }
            }
            password.UserId = _context.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault().Id;
            password.EncryptedPassword = Helpers.Encryptor.Encrypt(password.EncryptedPassword);
            ModelState.Remove("User");
            if (ModelState.IsValid)
            {
                _context.Add(password);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", password.UserId);


            _logger.LogInformation("Successful Password creation attempt by user " + User.Identity.Name);

            return View(password);
        }

        // GET: Passwords/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Passwords == null)
            {
                return NotFound();
            }

            var password = await _context.Passwords.FindAsync(id);
            if (password == null)
            {
                return NotFound();
            }

            if (password.UserId != _context.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault().Id)
            {
                return Unauthorized();
            }

            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", password.UserId);
            return View(password);
        }

        // POST: Passwords/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ServiceName,EncryptedPassword,UserId")] Password password)
        {
            if (id != password.Id)
            {
                return NotFound();
            }
            PasswordValidator passValidation = new PasswordValidator();
            FluentValidation.Results.ValidationResult validationResult = passValidation.Validate(password);
            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError("UserError", error.ErrorMessage);
                }
            }

            password.UserId = _context.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault().Id;
            password.EncryptedPassword = Helpers.Encryptor.Encrypt(password.EncryptedPassword);
            ModelState.Remove("User");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(password);
                    await _context.SaveChangesAsync();
                    _logger.LogInformation("Successful Password edition attempt by user " + User.Identity.Name);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PasswordExists(password.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", password.UserId);
            return View(password);
        }

        // GET: Passwords/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Passwords == null)
            {
                return NotFound();
            }

            var password = await _context.Passwords
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (password == null)
            {
                return NotFound();
            }


            if (password.UserId != _context.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault().Id)
            {
                return Unauthorized();
            }

            return View(password);
        }

        // POST: Passwords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Passwords == null)
            {
                return Problem("Entity set 'MyDbContext.Passwords'  is null.");
            }
            var password = await _context.Passwords.FindAsync(id);

            if (password != null)
            {

                if (password.UserId != _context.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault().Id)
                {
                    return Unauthorized();
                }
                _context.Passwords.Remove(password);
                _logger.LogInformation("Successful Password removal attempt by user " + User.Identity.Name);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PasswordExists(int id)
        {
          return (_context.Passwords?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GLS_BlazorMVC_PoC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GLS_BlazorMVC_PoC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GLS_BlazorMVC_PoC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GLS_BlazorMVC_PoC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link">Welcome, @User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Passwords" asp-action="Index">Manage Passwords</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GLS_BlazorMVC_PoC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>